sudo: required
dist: trusty
language: cpp

compiler:
    - gcc
    - clang

os:
    - linux
    - osx

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    packages:
    - gcc-4.9
    - g++-4.9
    - cmake
    - valgrind
    - libboost-dev                 #needed for thrift cpp compilation
    - libboost-program-options-dev #needed for thrift cpp compilation
    - libboost-test-dev            #needed for thrift cpp compilation
    - libssl-dev                   #needed for thrift cpp compilation
    - libtool                      #needed for thrift cpp compilation
    - bison                        #needed for thrift cpp compilation
    - flex                         #needed for thrift cpp compilation
    - pkg-config                   #needed for thrift cpp compilation

before_install:
    - pushd thirdparty
    # thrift cpp
    - >
      if [ $TRAVIS_OS_NAME == osx ]; then
        brew update &&
        brew install thrift;
      fi
    - >
      if [ $TRAVIS_OS_NAME == linux ]; then
        wget http://archive.apache.org/dist/thrift/0.9.1/thrift-0.9.1.tar.gz &&
        tar xfz thrift-0.9.1.tar.gz &&
        pushd thrift-0.9.1 &&
        ./configure CXXFLAGS='-fPIC' --without-qt4 --without-c_glib --without-csharp --without-java --without-erlang --without-nodejs --without-lua --without-python --without-perl --without-php --without-php_extension --without-ruby --without-haskell --without-go --without-d --with-cpp --prefix=$HOME/local &&
        make clean &&
        make install &&
        popd;
      fi
    # snappy and lz4
    - ./download_thirdparty.sh
    - ./build_thirdparty.sh
    - popd

before_script:
    - export CC="gcc-4.9"
    - export CXX="g++-4.9"
    - mkdir build
    - cd build
    - THRIFT_HOME=$HOME/local SNAPPY_HOME=$TRAVIS_BUILD_DIR/thirdparty/installed LZ4_HOME=$TRAVIS_BUILD_DIR/thirdparty/installed cmake ..

script: make
