sudo: required
dist: precise
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    - llvm-toolchain-precise-3.7
    packages:
    - clang-format-3.7
    - clang-tidy-3.7
    - gcc-4.9
    - g++-4.9
    - gcov
    - cmake
    - valgrind
    - libboost-dev                 #needed for thrift cpp compilation
    - libboost-program-options-dev #needed for thrift cpp compilation
    - libboost-test-dev            #needed for thrift cpp compilation
    - libssl-dev                   #needed for thrift cpp compilation
    - libtool                      #needed for thrift cpp compilation
    - bison                        #needed for thrift cpp compilation
    - flex                         #needed for thrift cpp compilation
    - pkg-config                   #needed for thrift cpp compilation

matrix:
  include:
  - compiler: gcc
    os: linux
    before_script:
    - source $TRAVIS_BUILD_DIR/ci/before_script_travis.sh
    - cmake -DCMAKE_CXX_FLAGS="-Werror" -DPARQUET_TEST_MEMCHECK=ON -DPARQUET_GENERATE_COVERAGE=1 $TRAVIS_BUILD_DIR
    - export PARQUET_TEST_DATA=$TRAVIS_BUILD_DIR/data
  - compiler: clang
    os: linux
  - os: osx
    compiler: clang
    addons:

language: cpp
before_install:
- mkdir $TRAVIS_BUILD_DIR/parquet-build
- pushd $TRAVIS_BUILD_DIR/parquet-build

before_script:
- source $TRAVIS_BUILD_DIR/ci/before_script_travis.sh
- cmake -DCMAKE_CXX_FLAGS="-Werror" $TRAVIS_BUILD_DIR
- export PARQUET_TEST_DATA=$TRAVIS_BUILD_DIR/data

script:
- $TRAVIS_BUILD_DIR/ci/travis_script_cpp.sh
